variables:
  ARTIFACT_NAME: aws-beanstalk-integration-demo-v$CI_PIPELINE_IID.jar
  APP_NAME: aws-s3-integration-demo

stages:
- build
- test
- deploy

build:
  stage: build
  image: openjdk:12-alpine
  only:
      refs:
        - merge_requests
        - main
        - develop
  script:
    - ./gradlew build
    - mv ./build/libs/aws-beanstalk-integration-demo-0.0.1.jar ./build/libs/$ARTIFACT_NAME
  artifacts:
    paths:
      - ./build/libs/

test:
  stage: test
  image: openjdk:12-alpine
  script:
    ./gradlew test
  only:
    refs:
      - merge_requests
  artifacts:
    when: always
    paths:
      - build/reports/tests
    reports:
      junit: build/test-results/test/*.xml

deploy:
  stage: deploy
  image:
    name: banst/awscli
    entrypoint: [""]
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
      variables:
        DEPLOY_ENV: "production"
    - if: $CI_COMMIT_BRANCH == "develop"
      variables:
        DEPLOY_ENV: "development"
  script:
    - aws configure set region us-east-1
    - aws s3 cp ./build/libs/$ARTIFACT_NAME s3://$AWS_S3_BUCKET/$ARTIFACT_NAME
    - aws elasticbeanstalk create-application-version --application-name $APP_NAME --version-label $CI_PIPELINE_IID --source-bundle S3Bucket=$AWS_S3_BUCKET,S3Key=$ARTIFACT_NAME
    - aws elasticbeanstalk update-environment --application-name $APP_NAME --environment-name=$DEPLOY_ENV --version-label=$CI_PIPELINE_IID